const ActionTypes = {
  LOADING: "LOADING",
  GET_COUNTRIES: "GET_COUNTRIES",
  SET_COUNTRIES: "SET_COUNTRIES",
  ALL_COUNTRIES_FAIL: "ALL_COUNTRIES_FAIL",
  GET_SEARCH_COUNTRIES: "GET_SEARCH_COUNTRIES",
  SET_SEARCH_COUNTRIES: "SET_SEARCH_COUNTRIES",
  SEARCH_COUNTRIES_FAIL: "SEARCH_COUNTRIES_FAIL",
  FILTER_COUNTRIES: "FILTER_COUNTRIES",
  FILTER_COUNTRIES_FAIL: "FILTER_COUNTRIES_FAIL",
  SET_THEME: "SET_THEME",
  GET_COUNTRY_DETAILS: "GET_COUNTRY_DETAILS",
};

export default ActionTypes;
